version: '3'

networks:
    demo-network:
        driver: bridge

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:5.0.0
        ports:
            - 2181:2181
        environment: 
            ZOOKEEPER_CLIENT_PORT: 2181
        container_name: zookeeper
        networks: 
            - demo-network
    kafka:
        image: confluentinc/cp-kafka:5.0.0
        container_name: kafka
        depends_on: 
            - zookeeper
        ports:
            - 9092:9092
        environment: 
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_ADVERTISED_HOST_NAME: kafka
        networks: 
            - demo-network
    ftp-server:
        image: atmoz/sftp
        container_name: ftp-server
        volumes:
            - /home/rebecca/IdeaProjects/IoTDataflow_v.1.2.0/data/iotpartition:/home/ftpuser/ftp
        networks: 
            - demo-network
        command: ftpuser:1234
    kafka-connect-configuration:
        build:
            context: kafka_connect_configuration
            dockerfile: Dockerfile
        container_name: kafka-connect-configuration
        depends_on:
            - zookeeper
            - kafka
            - ftp-server
        environment:
            ZOOKEEPER_HOSTS: "zookeeper:2181"
            KAFKA_TOPIC: "e-coating-streaming"
        networks: 
            - demo-network
    consumer:
        build: kafka_consumer_app/
        container_name: consumer
        depends_on: 
            - kafka
            - zookeeper
            - kafka-connect-configuration
        ports:
            - 8080:5001
        environment: 
            KAFKA_TOPIC: "e-coating-streaming"
            KAFKA_HOST: "kafka:9092"
        networks: 
            - demo-network
    db:
        image: mysql
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: e_coating
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        volumes:
            - /home/rebecca/IdeaProjects/IoTDataflow_v.1.2.0/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - demo-network
    adminer:
        image: adminer
        restart: always
        ports:
            - 3307:8080
        networks:
            - demo-network